[pytest]
testpaths = cellmil/__tests__
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --html=test_reports/report.html 
    --self-contained-html
    --tb=short
    --strict-markers
    --disable-warnings
    -v
    --capture=no
    --ignore=__legacy__
    --ignore=__legacy__/
markers =
    pipeline: Pipeline tests
    dataset: Dataset tests
    model: Model tests
    training: Training tests
filterwarnings =
    ignore::UserWarning
    ignore::DeprecationWarning
    ignore::FutureWarning
norecursedirs = __legacy__ .git .tox *.egg build dist